latchset/tang-operator

- Makefile
- README.md
- bundle/manifests/tang-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- controllers/tangserver_controller.go
- controllers/tangserver_controller_client.go
- controllers/tangserver_controller_keyhandler.go
- controllers/tangserver_controller_keystatus.go
- controllers/tangserver_controller_podfile.go
- controllers/tangserver_controller_test.go
- tools/api_tools/delete_one_hidden_key.sh
In current implementation, deletion of hidden keys can only be done by removing all of the hidden keys.
This PR will handle the removal of selective hidden keys, by specifying the required SHA1 - SHA256 of the key or keys that will be removed.
> Implementation of selective hidden keys deletion

- .github/workflows/go.yml
- .github/workflows/scripts/retrieve_and_run_operator_sdk.sh
- Makefile
- README.md
- bundle.Dockerfile
- bundle/manifests/tang-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/manager/kustomization.yaml
- controllers/tangserver_controller_pod.go
> Avoid execution as root for tang server pod

- README.md
> Include cross-compilation instructions on README.md

- .github/workflows/go.yml
- .github/workflows/scripts/retrieve_and_run_operator_sdk.sh
> Dump olm status before next step

- .github/workflows/go.yml
- .github/workflows/scripts/retrieve_and_run_operator_sdk.sh
> Update to latest version of operator-sdk (v1.26.0) and minikube

- .github/workflows/go.yml
> Fail fast if error in compilation

- controllers/tangserver_controller_deployment_test.go
> Extend tang operator deployment test coverage

- controllers/tangserver_controller_test.go
> Extend tang operator controller test coverage

- tools/change-readme-version.sh
> Script to change versions in README.md

- Makefile
- README.md
- bundle.Dockerfile
- bundle/manifests/tang-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/manager/kustomization.yaml
- config/samples/daemons_v1alpha1_tangserver.yaml
- controllers/tangserver_controller_imageinfo.go
- operator_configs/jpm_namespace/daemons_v1alpha1_tangserver.yaml
- operator_configs/main/daemons_v1alpha1_tangserver.yaml
> Use rhel9 tang container image

- .github/workflows/scripts/retrieve_and_run_operator_sdk.sh
> Fail on deployment or scorecard execution

- README.md
> Add cross compilation section to index

- controllers/tangserver_controller.go
> Do not publicize handleHiddenKeys

- tools/test_memleak.sh
> Fix shellcheck reported issues for test_memleak.sh

- .github/workflows/go.yml
> Decrease timeout for deployment to 5 minutes

- .github/workflows/spellcheck.yml
> Include spellcheck Github action execution on main

- tools/api_tools/show_keys.sh
> Show correct usage for show_keys.sh api script

- tools/api_tools/show_keys.sh
> Fix issues reported by shellcheck

- tools/step_by_step/step_by_step_00.sh
> Fix issues reported by shellcheck for step_by_step

- tools/api_tools/key_rotate.sh
> Fix shellcheck issues for key_rotate.sh script

- controllers/suite_test.go
- controllers/tangserver_controller.go
- controllers/tangserver_controller_deployment.go
- controllers/tangserver_controller_keyhandler.go
- controllers/tangserver_controller_keystatus.go
- controllers/tangserver_controller_service.go
> Fix issues reported by staticcheck

- tools/cluster_tools/add_cluster.sh
> Fix shellcheck issues for add_cluster.sh script

- tools/step_by_step/step_by_step_00.sh
> Fix shellcheck issue for step_by_step_00.sh script

- tools/api_tools/api_explore.sh
> Fix shellcheck issues in api_explore.sh script

- tools/api_tools/api_explore.sh
> Use oc get --raw instead of curl to access API

- .github/workflows/staticcheck.yaml
> Include staticcheck Github action

- test_containers/fedora_tang_server/tangd-health-check
> Fix shellcheck issues on tangd-health-check script

- .gitignore
> Include cluster bot files in .gitignore

- test_containers/fedora_tang_server/tangd-entrypoint
> Fix shellcheck issues for tangd-entrypoint script

- .github/workflows/go.yml
> Rename Verify to verify Github action

- .github/workflows/staticcheck.yaml
- README.md
> Limit staticcheck execution to .go files

- .github/workflows/go.yaml
- .github/workflows/shellcheck.yaml
- README.md
> Avoid shellcheck/verify Github actions for .md

- README.md
> Minimum change to test Github actions execution

- .github/workflows/cross_compile.yaml
- .github/workflows/deploy.yaml
- Makefile
- README.md
- api/v1alpha1/groupversion_info.go
- api/v1alpha1/tangserver_types.go
- config/crd/bases/daemons.redhat.com_tangservers.yaml
- config/rbac/role.yaml
- controllers/tangserver_controller.go
- controllers/tangserver_controller_client.go
- controllers/tangserver_controller_keyhandler.go
- controllers/tangserver_controller_keyhandler_test.go
Tested with 1.19 and 1.20
Resolves: #89
> Fix to support latest versions of Go

- Makefile
- README.md
- bundle.Dockerfile
- bundle/manifests/daemons.redhat.com_tangservers.yaml
- bundle/manifests/tang-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/manager/kustomization.yaml
> Release new version (0.0.27)

- README.md
> Remove CLUSTER related unit tests until fixed

- .github/workflows/cross_compile.yaml
- .github/workflows/deploy.yaml
- .github/workflows/staticcheck.yaml
> Avoid Node.js Github action version warnings

- .github/workflows/shellcheck.yaml
- .github/workflows/spellcheck.yaml
- .github/workflows/staticcheck.yaml
> Homogeneize Github action names

- .github/workflows/scripts/retrieve_and_run_operator_sdk.sh
> Verify checksum for operator-sdk

- .github/workflows/deploy.yaml
> Use latest version of setup-go Github action

- README.md
> Update test coverage execution percentage

- controllers/tangserver_controller.go
- controllers/tangserver_controller_keyhandler.go
- controllers/tangserver_controller_keystatus.go
- controllers/tangserver_controller_log.go
- controllers/tangserver_controller_service.go
- controllers/tangserver_controller_service_test.go
> Avoid passing log object everywhere

- Makefile
- README.md
- bundle/manifests/tang-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> Release version v0.0.28

- .wordlist.txt
- README.md
> Add status badges for different Github actions

- README.md
> One badge per line in README.md

- .github/workflows/cross_compile.yaml
- .github/workflows/deploy.yaml
> Avoid compilation Github actions for .wordlist.txt

- .github/workflows/shellcheck.yaml
> Avoid shellcheck action for .wordlist.txt changes

- README.md
> Update unit test execution coverage information

- tools/cluster_tools/add_cluster.sh
> Adding license header to add_cluster.sh

- .wordlist.txt
- README.md
> Include Golang CI lint status badge in README.md

- README.md
> Include license badge

- .github/workflows/staticcheck.yaml
> Set latest staticcheck version

- README.md
> Remove cluster test from README.md

- .gitignore
- tools/index_tools/tang_catalog_source_template.yaml
- tools/index_tools/tang_install_catalog.sh
> Fix index scripts

- tools/index_tools/tang_install_catalog.sh
> Include list option to show just install info

- tools/scan_tools/scan_tang.yaml
> Add basic file for DAST

- tools/api_tools/api_explore.sh
- tools/api_tools/delete_one_hidden_key.sh
- tools/api_tools/key_rotate.sh
- tools/api_tools/show_keys.sh
- tools/change-readme-version.sh
- tools/cluster_tools/add_cluster.sh
- tools/index_tools/tang_index.sh
- tools/index_tools/tang_install_catalog.sh
- tools/index_tools/tang_uninstall_catalog.sh
- tools/step_by_step/step_by_step_00.sh
- tools/test_memleak.sh
> Homogeneize licensing (Apache 2.0 to all)

- Makefile
- README.md
- bundle/manifests/tang-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> Create release 1.0.0 (GA candidate)

- README.md
Update README.md (fix minor typo)
> Update README.md (fix minor typo)

- tools/scan_tools/tang_operator_template.yaml
> Groom DAST scan tool template

- .github/dependabot.yaml
> Add dependabot to handle dependencies

- operator_configs/clevis/clevis.yaml
- operator_configs/fedora/daemons_v1alpha1_tangserver.yaml
- operator_configs/jpm_namespace/daemons_v1alpha1_tangserver.yaml
- operator_configs/main/daemons_v1alpha1_tangserver.yaml
- operator_configs/main_entry_test/daemons_v1alpha1_tangserver.yaml
- operator_configs/minimal-keyretrieve-deletehiddenkeys/daemons_v1alpha1_clusterrole.yaml
- operator_configs/minimal-keyretrieve-deletehiddenkeys/daemons_v1alpha1_clusterrolebinding.yaml
- operator_configs/minimal-keyretrieve-deletehiddenkeys/daemons_v1alpha1_tangserver.yaml
- operator_configs/minimal-keyretrieve-multireplica-deletehiddenkeys/daemons_v1alpha1_clusterrole.yaml
- operator_configs/minimal-keyretrieve-multireplica-deletehiddenkeys/daemons_v1alpha1_clusterrolebinding.yaml
- operator_configs/minimal-keyretrieve-multireplica-deletehiddenkeys/daemons_v1alpha1_tangserver.yaml
- operator_configs/minimal-keyretrieve-multireplica/daemons_v1alpha1_clusterrole.yaml
- operator_configs/minimal-keyretrieve-multireplica/daemons_v1alpha1_clusterrolebinding.yaml
- operator_configs/minimal-keyretrieve-multireplica/daemons_v1alpha1_tangserver.yaml
- operator_configs/minimal-keyretrieve-noclusterroles/daemons_v1alpha1_tangserver.yaml
- operator_configs/minimal-keyretrieve-refreshtimer/daemons_v1alpha1_clusterrole.yaml
- operator_configs/minimal-keyretrieve-refreshtimer/daemons_v1alpha1_clusterrolebinding.yaml
- operator_configs/minimal-keyretrieve-refreshtimer/daemons_v1alpha1_tangserver.yaml
- operator_configs/minimal-keyretrieve-rotate/daemons_v1alpha1_clusterrole.yaml
- operator_configs/minimal-keyretrieve-rotate/daemons_v1alpha1_clusterrolebinding.yaml
- operator_configs/minimal-keyretrieve-rotate/daemons_v1alpha1_tangserver.yaml
- operator_configs/minimal-keyretrieve/daemons_v1alpha1_clusterrole.yaml
- operator_configs/minimal-keyretrieve/daemons_v1alpha1_clusterrolebinding.yaml
- operator_configs/minimal-keyretrieve/daemons_v1alpha1_tangserver.yaml
- operator_configs/minimal-multireplica/daemons_v1alpha1_tangserver.yaml
- operator_configs/minimal/daemons_v1alpha1_tangserver.yaml
> Fix operator_configs issues reported by yamllint

- .github/workflows/yamllint.yaml
> Include yamllint Github action

- Makefile
- README.md
- bundle/manifests/tang-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> Release 1.0.3 version (GA candidate)

- Makefile
- README.md
- bundle/manifests/tang-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> Release 1.0.5 version (GA candidate)

- README.md
This commit includes information on where to find Function Tests repository
Resolves: #200
> Include reference to Function Tests repository

- README.md
> Chnage README.md to test yamllint Github Action

- Makefile
- bundle/manifests/tang-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> Release 1.0.6 (GA candidate)

- Makefile
> Allow using podman by setting new make rules

- tools/test_memleak/test_memleak.sh
> Fix test-memleak configuration path

- .wordlist.txt
- README.md
> Show compilation steps through Podman

- .wordlist.txt
- README.md
> Show compilation steps through Podman (#228)

- README.md
> Clarify v1.0.6 as released version

- Makefile
- README.md
- bundle.Dockerfile
- bundle/manifests/tang-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/manager/kustomization.yaml
> Release 1.0.7 (GA candidate re-release)

- Makefile
> Recover correct IMG_TAG_BASE

- README.md
> Include cross-compilation as subsection

- README.md
> Include reference to operator in OpenShift

- README.md
> Include current compilation requirements

- README.md
> Include golang installation link in references

- .github/workflows/cross_compile.yaml
- .github/workflows/deploy.yaml
- .github/workflows/golangci-lint.yaml
- .github/workflows/multi-arch_images_build.yaml
- .github/workflows/shellcheck.yaml
- .github/workflows/spellcheck.yaml
- .github/workflows/staticcheck.yaml
- .github/workflows/yamllint.yaml
> Use latest action versions to avoid Node16 issues

- README.md
> Fix README.md to correctly list Github actions

- README.md
> Fix cross-compilation README.md documentation

- .github/workflows/cross_compile.yaml
> Include additional cross-compilation architectures

- README.md
> Include documentation of cross compilation archs

- .wordlist.txt
- Makefile
- README.md
- bundle/manifests/tang-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> Release 1.0.8 (ServiceType/ClusterIP CRD config)

- .wordlist.txt
- README.md
> Include Killercoda demo on README.md links

- .github/workflows/multi-arch_images_build.yaml
> Fix multi arch build to use Node20 Github action

- README.md
> Adapt README.md to include alert appropriately

- README.md
> Fix README.md ortographic issue

- .github/workflows/deploy.yaml
- .github/workflows/scripts/retrieve_and_run_operator_sdk.sh
- tools/cluster_tools/add_cluster.sh
> Avoid terminal close due to sourced add_cluster.sh

- CONTRIBUTING.md
> Add CONTRIBUTING.md as contribution guidelines

- .github/dependabot.yml
> Include dependabot for GH actions and go pkgs

- README.md
> Fix issues reported by LanguageTool

- Dockerfile
- Makefile
- README.md
- bundle/manifests/tang-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> Release version v1.0.11
